apiVersion: v1
kind: Service
metadata:
  name: novelty-predict-service
spec:
  type: LoadBalancer
  selector:
    app: novelty-predict
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
