FROM python:3.9

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt


COPY novelty_model.pkl ./
CMD ["uvicorn", "novelty_predict_api:app", "--host", "0.0.0.0", "--port", "80"]

