FROM python:3.10-slim

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir fastapi uvicorn pandas scikit-learn joblib

CMD ["uvicorn", "user_staples_api:app", "--host", "0.0.0.0", "--port", "80"]
