name: Build and Push to ACR

on:
  push:
    branches:
      - main  # or change to whatever branch you're using

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: shelflife.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push novelty-predict-api
        run: |
          docker buildx build --platform linux/amd64 \
            -t shelflife.azurecr.io/novelty-predict-api:latest \
            --push ./novelty-predict-api

      - name: Build and push user-staples-api
        run: |
          docker buildx build --platform linux/amd64 \
            -t shelflife.azurecr.io/user-staples-api:latest \
            --push ./user-staples-api
